# Use small container and not VM:
sudo: false

# Choose a build environment:
dist: xenial

# Only clone the repository tip & track all branches
git:
  depth: false

notifications:
  slack:
    rooms:
      secure: VYkYJktT9Cu/aRGQccZrFdjqgFZKq65k5CIMF3i2QmMfwXVzgFojY2XyRP+VB/idopI3iAtMz81dHXUBNyX50JtftFRL4R3ic+7eqDJu30E9kerjDbFeveISVLLTTTvuG13sME6UclgKycF9Cma68Q9+MqSxCMNnu1X8LvqKofZLG2xy9UMUzJx39a9D/+oyQUtpNRopxxvG9bpyOoOp9H+lJLlDiiBpNea07l0r+9XlgfbM1UiqdxBuZMzbWoOE2QKv+JBj1PrHyS0LNwnbM6k6VNx0BWMa3C9NSnvKp7vF0aOSR9UslCjAcE/eg8xzNu/A/xNhgxF30Uc4rzH99E7f4z+G4/Qure2p+Y+jz0IBtsmLDfHWwEL2BPyaqTbMwEJz8oYKYYrb9UtjYLvn4LtbgtwAqqDgbdpMlS5pB5P/klblDsR3YsKkLwYPfZeAKXyLfMMuVpEILE7nS9ntyjw5I6tCK23PryeuJQad34C7iFQXeC42WvgYV5x+F+ZbFaY58GdVWER5X66yp4Jxgo2uo0tCdjpN8PlgQOjDSl7tgMBFcLu+TXhpYZQ1Kr/nV2f2Nb2+MDs5Eb/05yTeZzNBMzMLbKNZcAJgP3kyAAgnkUuDaVYLUcZ2q5CJkokWLWTg6fLzcoNZ1kdmtU14FwOuj0sczO42AiAqYP4EOls=
    on_pull_requests: false
    on_success: change # Send a Slack notification when the build goes from failed to success (and vice-versa)
    on_error: always # Send a Slack notification when the build is failing on master
    email: false

env:
  global:
    - WALLET_CLI_JORMUNGANDR=$HOME/.local/bin/cardano-wallet-jormungandr
    - WALLET_CLI_JORMUNGANDR_CHECKSUM=$HOME/.local/bin/cardano-wallet-jormungandr.sha256
    - WALLET_CLI_JORMUNGANDR_TARGZ=$HOME/.local/bin/cardano-wallet-jormungandr.tar.gz
    - STACK_WORK_CACHE=$HOME/.stack/stack-work.tar.gz
    - PATH=$PATH:$HOME/.local/bin
    - LOCAL_MIX_DIR=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/hpc/

# We use a hybrid setup with Rust and Haskell, so we handle the compilation ourselves
language: generic

# Deactivate builds on branches but `master` and the bors branches.
# CI is still triggered by PRs).
# We do also CI to kick in when pushing a tag `git push --tags` for releases.
if: "(branch = master) OR (tag =~ ^v)"

# Caching so the next build will be fast too:
cache:
  timeout: 1337
  directories:
  - $HOME/.stack

before_cache:
  # Remove extra unused and heavy stuff from stack directory to avoid caching useless files
  - rm -rf $HOME/.stack/programs/x86_64-linux/ghc-*.tar.*
  - rm -rf $HOME/.stack/indices/Hackage/00-index.tar $HOME/.stack/indices/Hackage/00-index.tar.gz
  - find $HOME/.stack/programs/x86_64-linux/ghc-*/lib/ghc-* -type f -name *_p.a -delete

before_install:
  - mkdir -p $HOME/.local/bin
  - tar xzf $STACK_WORK_CACHE || echo "no .stack-work yet"
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
  - travis_retry stack --no-terminal setup

# Ensure necessary system libraries are present:
addons:
  apt:
    packages:
      - libgmp-dev
      - librocksdb-dev
      - libsystemd-dev

# Define custom set of stages
stages:
- cache 💾
- build project 🔨
- deploy 🚀

jobs:
  fast_finish: true
  include:
  - stage: cache 💾
    if: type != pull_request AND (branch = master OR tag =~ ^v)
    name: "Caching Dependencies"
    script:
    - stack --no-terminal build --only-snapshot
    - stack --no-terminal build --only-dependencies
    - tar czf $STACK_WORK_CACHE .stack-work

  - stage: build project 🔨
    if: type != pull_request AND (branch = master OR tag =~ ^v)
    name: "Compiling Project"
    script:
    - stack --no-terminal build --haddock --no-haddock-deps --skip cardano-wallet-core-integration
    - tar czf $STACK_WORK_CACHE .stack-work lib/**/.stack-work

  - stage: deploy 🚀
    if: type != pull_request AND (branch = master OR tag =~ ^v)
    name: "Haddock"
    script:
    - mkdir -p haddock/edge api/edge
    - cp -Rv specifications/api/* api/edge
    - mv $(stack path --local-doc-root)/* haddock/edge
    - git checkout --orphan gh-pages-deploy && git reset
    - git add api haddock && git commit -m $TRAVIS_COMMIT
    - git fetch origin
    - git checkout gh-pages && git merge -X theirs --no-commit --no-ff --allow-unrelated-histories - && git commit --allow-empty --no-edit
    - git push -f -q https://WilliamKingNoel-Bot:$GITHUB_ACCESS_TOKEN@github.com/input-output-hk/cardano-wallet gh-pages &>/dev/null

  - stage: deploy 🚀
    if: type != pull_request AND tag =~ ^v
    name: "Executables"
    script:
    # Create optimized binaries and checksums
    - stack --no-terminal install

    # Bundle cardano-wallet-jormungandr
    - cp $WALLET_CLI_JORMUNGANDR cardano-wallet
    - tar czf $WALLET_CLI_JORMUNGANDR_TARGZ cardano-wallet
    - sha256sum $WALLET_CLI_JORMUNGANDR | head -c 64 > $WALLET_CLI_JORMUNGANDR_CHECKSUM
    - ls $WALLET_CLI_JORMUNGANDR_TARGZ
    - ls $WALLET_CLI_JORMUNGANDR_CHECKSUM

    # Deploy documentation snapshot
    - mkdir -p haddock/$TRAVIS_TAG api/$TRAVIS_TAG
    - cp -Rv specifications/api/* api/$TRAVIS_TAG
    - mv $(stack path --local-doc-root)/* haddock/$TRAVIS_TAG
    - git checkout --orphan gh-pages-deploy && git reset
    - git add api haddock && git commit -m $TRAVIS_COMMIT
    - git checkout gh-pages && git merge -X theirs --no-commit --no-ff --allow-unrelated-histories - && git commit --allow-empty --no-edit
    - travis_retry git push -f -q https://WilliamKingNoel-Bot:$GITHUB_ACCESS_TOKEN@github.com/input-output-hk/cardano-wallet gh-pages &>/dev/null

    deploy:
      provider: releases
      api_key: $GITHUB_ACCESS_TOKEN
      draft: true # Allow editing the release before publishing it officially on GitHub
      skip_cleanup: true # Make sure that files from the previous stages aren't cleaned up
      file:
        - $WALLET_CLI_JORMUNGANDR_TARGZ
        - $WALLET_CLI_JORMUNGANDR_CHECKSUM
      on:
        repo: input-output-hk/cardano-wallet
        branch: master
        tags: true # Only release when a tag is pushed
