# Use small container and not VM:
sudo: false

# Choose a build environment:
dist: xenial

# Only clone the repository tip & track all branches
git:
  depth: false

env:
  global:
    - WALLET_SERVER=$HOME/.local/bin/cardano-wallet-server
    - WALLET_SERVER_CHECKSUM=$HOME/.local/bin/cardano-wallet-server.sha256
    - WALLET_LAUNCHER=$HOME/.local/bin/cardano-wallet-launcher
    - WALLET_LAUNCHER_CHECKSUM=$HOME/.local/bin/cardano-wallet-launcher.sha256
    - STACK_WORK_CACHE=$HOME/.local/stack-work.tar.gz
    - PATH=$PATH:$HOME/.cargo/bin:$HOME/.local/bin


# Use the Travis Rust build tools for cardano-http-bridge.
language: rust

# Deactivate builds on branches but `master` (CI is still triggered by PRs).
# We do also CI to kick in when pushing a tag `git push --tags` for releases.
if: (branch = master) OR (tag =~ ^v)

# Caching so the next build will be fast too:
cache:
  timeout: 1337
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc
  - $HOME/.cargo

before_cache:
  - rm -rf $HOME/.cargo/registry # Don't cache cargo's registry

# Ensure necessary system libraries are present:
addons:
  apt:
    packages:
      - libgmp-dev

# Define custom set of stages
stages:
- build 🔨
- checks 🔬
- deploy 🚀

jobs:
  fast_finish: true
  include:
  - stage: build 🔨
    name: "Stylish-Haskell"
    env: NO_CACHE=True
    script:
    - curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
    - git diff --exit-code # Exit if Stylish-Haskell yields any diff

  - stage: build 🔨
    name: "Compiling"
    script:
    - mkdir -p ~/.local/bin
    - test "$(cardano-http-bridge --version)" = "cardano-http-bridge 0.0.1" || travis_retry cargo install --git https://github.com/input-output-hk/cardano-http-bridge.git
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack --no-terminal setup
    - stack --no-terminal build --only-snapshot
    - stack --no-terminal build --only-dependencies
    - stack --no-terminal build --test --no-run-tests --coverage --haddock --no-haddock-deps
    - tar czf $STACK_WORK_CACHE .stack-work

  - stage: checks 🔬
    name: "HLint"
    script:
    - tar xzf $STACK_WORK_CACHE
    - curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  - stage: checks 🔬
    name: "Weeder"
    script:
    - tar xzf $STACK_WORK_CACHE
    - curl -sSL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .

  - stage: checks 🔬
    name: "Tests"
    script:
    - tar xzf $STACK_WORK_CACHE
    - travis_retry curl -L -o hermes-testnet.tar.gz https://github.com/input-output-hk/cardano-wallet/raw/data-integration-testing/hermes-testnet.tar.gz
    - tar xzf hermes-testnet.tar.gz -C $HOME
    - cardano-http-bridge --help
    - stack --no-terminal test --coverage
    - tar czf $STACK_WORK_CACHE .stack-work

  - stage: deploy 🚀
    if: type = push AND branch = master
    name: "Haddock"
    script:
    - tar xzf $STACK_WORK_CACHE
    - mkdir -p haddock && mv $(stack path --local-doc-root)/* haddock
    - git add haddock && git commit -m $TRAVIS_COMMIT
    - git checkout gh-pages && git cherry-pick -X theirs -n - && git commit --allow-empty --no-edit
    - git push -f -q https://WilliamKingNoel-Bot:$GITHUB_ACCESS_TOKEN@github.com/input-output-hk/cardano-wallet gh-pages &>/dev/null

  - stage: deploy 🚀
    if: type = push AND branch = master
    name: "Coveralls"
    script:
    - tar xzf $STACK_WORK_CACHE
    - export LTS=$(cat stack.yaml | grep resolver) # Extract the LTS from the stack.yaml
    - git clone https://github.com/rubik/stack-hpc-coveralls && cd stack-hpc-coveralls && git checkout 3d8352d5642ab214a7a574bd797880ae39595a44 && echo $LTS > stack.yaml
    - stack --no-terminal install
    - cd - && shc cardano-wallet unit

  - stage: deploy 🚀
    if: tag =~ ^v
    name: "Executables"
    script:
    - tar xzf $STACK_WORK_CACHE
    - stack --no-terminal install
    - sha256sum $WALLET_SERVER | head -c 64 > $WALLET_SERVER_CHECKSUM
    - ls $WALLET_SERVER
    - ls $WALLET_SERVER_CHECKSUM
    - sha256sum $WALLET_LAUNCHER | head -c 64 > $WALLET_LAUNCHER_CHECKSUM
    - ls $WALLET_LAUNCHER
    - ls $WALLET_LAUNCHER_CHECKSUM
    deploy:
      provider: releases
      api_key: $GITHUB_ACCESS_TOKEN
      draft: true # Allow editing the release before publishing it officially on GitHub
      skip_cleanup: true # Make sure that files from the previous stages aren't cleaned up
      file:
        - $WALLET_SERVER
        - $WALLET_SERVER_CHECKSUM
        - $WALLET_LAUNCHER
        - $WALLET_LAUNCHER_CHECKSUM
      on:
        repo: input-output-hk/cardano-wallet
        branch: master
        tags: true # Only release when a tag is pushed
