# Use small container and not VM:
sudo: false

# Choose a build environment:
dist: xenial

# Only clone the repository tip & track all branches
git:
  depth: false

notifications:
  slack:
    rooms:
      secure: VYkYJktT9Cu/aRGQccZrFdjqgFZKq65k5CIMF3i2QmMfwXVzgFojY2XyRP+VB/idopI3iAtMz81dHXUBNyX50JtftFRL4R3ic+7eqDJu30E9kerjDbFeveISVLLTTTvuG13sME6UclgKycF9Cma68Q9+MqSxCMNnu1X8LvqKofZLG2xy9UMUzJx39a9D/+oyQUtpNRopxxvG9bpyOoOp9H+lJLlDiiBpNea07l0r+9XlgfbM1UiqdxBuZMzbWoOE2QKv+JBj1PrHyS0LNwnbM6k6VNx0BWMa3C9NSnvKp7vF0aOSR9UslCjAcE/eg8xzNu/A/xNhgxF30Uc4rzH99E7f4z+G4/Qure2p+Y+jz0IBtsmLDfHWwEL2BPyaqTbMwEJz8oYKYYrb9UtjYLvn4LtbgtwAqqDgbdpMlS5pB5P/klblDsR3YsKkLwYPfZeAKXyLfMMuVpEILE7nS9ntyjw5I6tCK23PryeuJQad34C7iFQXeC42WvgYV5x+F+ZbFaY58GdVWER5X66yp4Jxgo2uo0tCdjpN8PlgQOjDSl7tgMBFcLu+TXhpYZQ1Kr/nV2f2Nb2+MDs5Eb/05yTeZzNBMzMLbKNZcAJgP3kyAAgnkUuDaVYLUcZ2q5CJkokWLWTg6fLzcoNZ1kdmtU14FwOuj0sczO42AiAqYP4EOls=
    on_pull_requests: false
    on_success: change # Send a Slack notification when the build goes from failed to success (and vice-versa)
    on_error: always # Send a Slack notification when the build is failing on master
    email: false

# We use a hybrid setup with Rust and Haskell, so we handle the compilation ourselves
language: generic

# Deactivate builds on branches but `master` and the bors branches.
# CI is still triggered by PRs).
# We do also CI to kick in when pushing a tag `git push --tags` for releases.
if: "(branch = master) OR (tag =~ /^v(2019|2020|2021)-(0[1-9]|1[0-2])-(0[1-9]|1[0-9]|2[0-9]|3[0-1])$/)"

# Define custom set of stages
stages:
- documentation 📚
- deploy 🚀

jobs:
  fast_finish: true
  include:
  - stage: documentation 📚
    if: type != pull_request AND (branch = master OR tag =~ ^v)
    name: "API Documentation"
    script:
    - mkdir -p api/edge
    - cp -Rv specifications/api/* api/edge
    - git checkout --orphan gh-pages-deploy && git reset
    - git add api && git commit -m $TRAVIS_COMMIT
    - git fetch origin
    - git checkout gh-pages && git merge -X theirs --no-commit --no-ff --allow-unrelated-histories - && git commit --allow-empty --no-edit
    - git push -f -q https://WilliamKingNoel-Bot:$GITHUB_ACCESS_TOKEN@github.com/input-output-hk/cardano-wallet gh-pages &>/dev/null

  - stage: deploy 🚀
    if: type != pull_request AND (tag =~ ^v OR commit_message =~ /TRAVIS_TRIGGER_RELEASE/)
    name: "Executables"
    script:
    ############################
    # cardano-wallet-shelley
    ############################

    # Fetch the linux archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-shelley-linux64/latest/download/1 | tar xz
    - find . -maxdepth 1 -type d -name "cardano-wallet-shelley-*" -exec mv \{} cardano-wallet-shelley-linux64 \;
    - mv cardano-wallet-shelley-linux64/cardano-wallet-shelley cardano-wallet-shelley-linux64/cardano-wallet
    - tar czf cardano-wallet-shelley-$TRAVIS_TAG-linux64.tar.gz cardano-wallet-shelley-linux64
    - rm -r cardano-wallet-shelley-linux64

    # Fetch the MacOS archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-shelley-macos64/latest/download/1 | tar xz
    - find . -maxdepth 1 -type d -name "cardano-wallet-shelley-*" -exec mv \{} cardano-wallet-shelley-macos64 \;
    - mv cardano-wallet-shelley-macos64/cardano-wallet-shelley cardano-wallet-shelley-macos64/cardano-wallet
    - tar czf cardano-wallet-shelley-$TRAVIS_TAG-macos64.tar.gz cardano-wallet-shelley-macos64
    - rm -r cardano-wallet-shelley-macos64

    # Fetch the Windows archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-shelley-win64/latest/download/1 --output cardano-wallet-shelley-win64.zip
    - unzip -d cardano-wallet-shelley-win64 cardano-wallet-shelley-win64.zip
    - mv cardano-wallet-shelley-win64/cardano-wallet-shelley.exe cardano-wallet-shelley-win64/cardano-wallet.exe
    - zip -r cardano-wallet-shelley-$TRAVIS_TAG-win64.zip cardano-wallet-shelley-win64
    - rm -r cardano-wallet-shelley-win64
    - rm cardano-wallet-shelley-win64.zip

    ############################
    # cardano-wallet-byron
    ############################

    # Fetch the linux archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-byron-linux64/latest/download/1 | tar xz
    - find . -maxdepth 1 -type d -name "cardano-wallet-byron-*" -exec mv \{} cardano-wallet-byron-linux64 \;
    - mv cardano-wallet-byron-linux64/cardano-wallet-byron cardano-wallet-byron-linux64/cardano-wallet
    - tar czf cardano-wallet-byron-$TRAVIS_TAG-linux64.tar.gz cardano-wallet-byron-linux64
    - rm -r cardano-wallet-byron-linux64

    # Fetch the MacOS archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-byron-macos64/latest/download/1 | tar xz
    - find . -maxdepth 1 -type d -name "cardano-wallet-byron-*" -exec mv \{} cardano-wallet-byron-macos64 \;
    - mv cardano-wallet-byron-macos64/cardano-wallet-byron cardano-wallet-byron-macos64/cardano-wallet
    - tar czf cardano-wallet-byron-$TRAVIS_TAG-macos64.tar.gz cardano-wallet-byron-macos64
    - rm -r cardano-wallet-byron-macos64

    # Fetch the Windows archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-byron-win64/latest/download/1 --output cardano-wallet-byron-win64.zip
    - unzip -d cardano-wallet-byron-win64 cardano-wallet-byron-win64.zip
    - mv cardano-wallet-byron-win64/cardano-wallet-byron.exe cardano-wallet-byron-win64/cardano-wallet.exe
    - zip -r cardano-wallet-byron-$TRAVIS_TAG-win64.zip cardano-wallet-byron-win64
    - rm -r cardano-wallet-byron-win64
    - rm cardano-wallet-byron-win64.zip

    ############################
    # cardano-wallet-jormungandr
    ############################

    # Fetch the linux archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-linux64/latest/download/1 | tar xz
    - find . -maxdepth 1 -type d -name "cardano-wallet-jormungandr-*" -exec mv \{} cardano-wallet-jormungandr-linux64 \;
    - mv cardano-wallet-jormungandr-linux64/cardano-wallet-jormungandr cardano-wallet-jormungandr-linux64/cardano-wallet
    - tar czf cardano-wallet-itn-$TRAVIS_TAG-linux64.tar.gz cardano-wallet-jormungandr-linux64
    - rm -r cardano-wallet-jormungandr-linux64

    # Fetch the MacOS archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-macos64/latest/download/1 | tar xz
    - find . -maxdepth 1 -type d -name "cardano-wallet-jormungandr-*" -exec mv \{} cardano-wallet-jormungandr-macos64 \;
    - mv cardano-wallet-jormungandr-macos64/cardano-wallet-jormungandr cardano-wallet-jormungandr-macos64/cardano-wallet
    - tar czf cardano-wallet-itn-$TRAVIS_TAG-macos64.tar.gz cardano-wallet-jormungandr-macos64
    - rm -r cardano-wallet-jormungandr-macos64

    # Fetch the Windows archive
    - travis_retry curl -L https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-win64/latest/download/1 --output cardano-wallet-jormungandr-win64.zip
    - unzip -d cardano-wallet-jormungandr-win64 cardano-wallet-jormungandr-win64.zip
    - mv cardano-wallet-jormungandr-win64/cardano-wallet-jormungandr.exe cardano-wallet-jormungandr-win64/cardano-wallet.exe
    - zip -r cardano-wallet-itn-$TRAVIS_TAG-win64.zip cardano-wallet-jormungandr-win64
    - rm -r cardano-wallet-jormungandr-win64
    - rm cardano-wallet-jormungandr-win64.zip

    # Deploy documentation snapshot
    - mkdir -p api/$TRAVIS_TAG
    - cp -Rv specifications/api/* api/$TRAVIS_TAG
    - git checkout --orphan gh-pages-deploy && git reset
    - git add api && git commit -m $TRAVIS_COMMIT
    - git checkout gh-pages && git merge -X theirs --no-commit --no-ff --allow-unrelated-histories - && git commit --allow-empty --no-edit
    - travis_retry git push -f -q https://WilliamKingNoel-Bot:$GITHUB_ACCESS_TOKEN@github.com/input-output-hk/cardano-wallet gh-pages &>/dev/null

    deploy:
      provider: releases
      api_key: $GITHUB_ACCESS_TOKEN
      draft: true # Allow editing the release before publishing it officially on GitHub
      skip_cleanup: true # Make sure that files from the previous stages aren't cleaned up
      file:
        # cardano-node / Byron
        - cardano-wallet-byron-$TRAVIS_TAG-linux64.tar.gz
        - cardano-wallet-byron-$TRAVIS_TAG-macos64.tar.gz
        - cardano-wallet-byron-$TRAVIS_TAG-win64.zip

        # cardano-node / Shelley
        - cardano-wallet-shelley-$TRAVIS_TAG-linux64.tar.gz
        - cardano-wallet-shelley-$TRAVIS_TAG-macos64.tar.gz
        - cardano-wallet-shelley-$TRAVIS_TAG-win64.zip

        # Jörmungandr / ITN
        - cardano-wallet-itn-$TRAVIS_TAG-linux64.tar.gz
        - cardano-wallet-itn-$TRAVIS_TAG-macos64.tar.gz
        - cardano-wallet-itn-$TRAVIS_TAG-win64.zip
      on:
        repo: input-output-hk/cardano-wallet
        branch: master
        tags: true # Only release when a tag is pushed
