- package:
  - name: cardano-wallet
  - section:
    - name: exe:cardano-wallet-launcher
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
  - section:
    - name: exe:cardano-wallet-launcher exe:cardano-wallet-server
    - message:
      - name: Module reused between components
      - module: Cardano.CLI
  - section:
    - name: exe:cardano-wallet-launcher test:integration test:unit
    - message:
      - name: Module reused between components
      - module:
        - Cardano.Launcher
        - Cardano.Launcher.POSIX
  - section:
    - name: test:integration
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
  - section:
    - name: test:unit
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows

