- package:
  - name: cardano-wallet
  - section:
    - name: bench:restore
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
  - section:
    - name: exe:cardano-wallet exe:cardano-wallet-launcher test:unit
    - message:
      - name: Module reused between components
      - module: Cardano.CLI
  - section:
    - name: exe:cardano-wallet-launcher
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
  - section:
    - name: exe:cardano-wallet-launcher test:integration test:unit bench:restore
    - message:
      - name: Module reused between components
      - module:
        - Cardano.Launcher
        - Cardano.Launcher.POSIX
  - section:
    - name: test:integration
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
    - message:
      - name: Weeds exported
      - module:
        - name: Test.Integration.Framework.DSL
        - identifier:
          - </>
          - expectError
          - expectSuccess
          - getFromResponse
      - module:
        - name: Test.Integration.Framework.Request
        - identifier:
          - ClientError
          - DecodeFailure
          - NonJson
          - None
          - unsafeRequest
  - section:
    - name: test:unit
    - message:
      - name: Module not compiled
      - module: Cardano.Launcher.Windows
    - message:
      - name: Weeds exported
      - module:
        - name: Spec
        - identifier: main
