- package:
  - name: cardano-wallet
  - section:
    - name: test:integration bench:latency
    - message:
      - name: Module reused between components
      - module: Cardano.Wallet.Shelley.Faucet
- package:
  - name: cardano-wallet-core
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Spec
        - identifier: main
  - section:
    - name: test:unit bench:db
    - message:
      - name: Module reused between components
      - module: Cardano.Wallet.DummyTarget.Primitive.Types
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.DummyTarget.Primitive.Types
        - identifier: genesisHash
- package:
  - name: cardano-wallet-core
  - section:
    - name: test:unit
    - message:
      - name: Weeds exported
      - module:
        - name: Cardano.Wallet.DB.StateMachine
        - identifier: showLabelledExamples
- package:
  - name: cardano-wallet-launcher
  - section:
    - name: library
    - message:
      - name: Module not compiled
      - module: Cardano.Startup.Windows
