status = [
  # Bors will merge if/when Travis succeeds.
  "continuous-integration/travis-ci/pr",
]
timeout_sec = 3600
required_approvals = 1
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
