# This resolver file contains a ghc-8.10.4-based stackage LTS, with a
# released cardano-node version, and supporting libraries.
#
# NOTE: Remember to update the version matrix in README.md when
# bumping the Cardano version.
resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/231870a3b785f569daef0596b3a1657324c9394a/snapshots/cardano-1.25.1-GHC-8.10.4.yaml

packages:
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/numeric
- lib/text-class
- lib/test-utils
- lib/shelley
- lib/strict-non-empty-containers

allow-newer: true

extra-deps:
- Cabal-3.4.0.0
- OddWord-1.0.2.0
- async-timer-0.2.0.0
- command-0.1.1
- markov-chain-usage-model-0.0.0
- parsec-3.1.14.0
- quickcheck-state-machine-0.7.0

# cardano-addresses-3.3.0
- git: https://github.com/input-output-hk/cardano-addresses
  commit: 55f174b32095e4264e0c75344caf34f4207a4e58
  subdirs:
    - command-line
    - core

# cardano-transactions master branch
- git: https://github.com/input-output-hk/cardano-transactions
  commit: efc3914f950438b70ebe20919bf6c0ecf93b3bbc

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

  # Using RDRAND instead of /dev/urandom as an entropy source for key
  # generation is dubious. Set the flag so we use /dev/urandom by default.
  cryptonite:
    support_rdrand: false

nix:
  shell-file: nix/stack-shell.nix
  # Disabling the pure nix-shell allows environment variables to be
  # passed down to tests. We need this for integration tests.
  pure: false
