resolver: lts-13.24
packages:
- .
- lib/bech32
- lib/core
- lib/core/test/integration
- lib/cli
- lib/launcher
- lib/text-class
- lib/http-bridge
- lib/jormungandr

extra-deps:
- base58-bytestring-0.1.0
- command-0.1.1
- generic-lens-1.1.0.0
- quickcheck-state-machine-0.6.0
- git: https://github.com/input-output-hk/cardano-crypto
  commit: 3c5db489c71a4d70ee43f5f9b979fcde3c797f2a

nix:
  shell-file: nix/stack-shell.nix
