# This resolver file contains a ghc-8.10.4-based stackage LTS, with a
# released cardano-node version, and supporting libraries.
#
# NOTE: Remember to update the version matrix in README.md when
# bumping the Cardano version.
resolver: cardano-1.25.1.yaml

packages:
- lib/core
- lib/core-integration
- lib/cli
- lib/launcher
- lib/numeric
- lib/text-class
- lib/test-utils
- lib/shelley
- lib/strict-non-empty-containers

extra-deps:
- unliftio-core-0.1.2.0
- OddWord-1.0.2.0
- generic-lens-1.1.0.0
- command-0.1.1
- quickcheck-state-machine-0.7.0
- markov-chain-usage-model-0.0.0
- parsec-3.1.14.0
- Cabal-3.2.1.0
- async-timer-0.2.0.0

# cardano-addresses-3.2.0
- git: https://github.com/input-output-hk/cardano-addresses
  commit: 05bd6d0b877d8fc440be83142935fa1e7a915916
  subdirs:
    - command-line
    - core

# cardano-transactions master branch
- git: https://github.com/input-output-hk/cardano-transactions
  commit: efc3914f950438b70ebe20919bf6c0ecf93b3bbc

flags:
  # Avoid a system library which causes difficulty with cross-compilation
  zip:
    disable-bzip2: true

  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

  # Using RDRAND instead of /dev/urandom as an entropy source for key
  # generation is dubious. Set the flag so we use /dev/urandom by default.
  cryptonite:
    support_rdrand: false

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

nix:
  shell-file: nix/stack-shell.nix
  # Disabling the pure nix-shell allows environment variables to be
  # passed down to tests. We need this for integration tests.
  pure: false


# !!! This can be dropped when cabal-3.4.0.0 is released !!!
#
#+BEGIN_STACK2CABAL
# package cardano-crypto
#   tests: False
#   benchmarks: False
#
# package contra-tracer
#   tests: False
#   benchmarks: False
#
# package iohk-monitoring
#   tests: False
#   benchmarks: False
#
# package zip
#   tests: False
#   benchmarks: False
#
# package cardano-crypto-praos
#   tests: False
#   benchmarks: False
#
# package byron-spec-ledger
#   tests: False
#   benchmarks: False
#
# package ouroboros-consensus-cardano
#   tests: False
#   benchmarks: False
#
# package small-steps
#   tests: False
#   benchmarks: False
#
# package small-steps-test
#   tests: False
#   benchmarks: False
#
# package ouroboros-consensus
#   tests: False
#   benchmarks: False
#
# package ouroboros-consensus-byron
#   tests: False
#   benchmarks: False
#
# package ouroboros-consensus-shelley
#   tests: False
#   benchmarks: False
#
# package ouroboros-consensus-mock
#   tests: False
#   benchmarks: False
#
# package cborg
#   tests: False
#   benchmarks: False
#
# package http-client
#   tests: False
#   benchmarks: False
#
# package goblins
#   tests: False
#   benchmarks: False
#
# package io-sim
#   tests: False
#   benchmarks: False
#
# package io-sim-classes
#   tests: False
#   benchmarks: False
#
# package shelley-spec-non-integral
#   tests: False
#   benchmarks: False
#
# package network-mux
#   tests: False
#   benchmarks: False
#
# package typed-protocols
#   tests: False
#   benchmarks: False
#
# package typed-protocols-examples
#   tests: False
#   benchmarks: False
#
# package cardano-prelude
#   tests: False
#   benchmarks: False
#
# package cardano-binary
#   tests: False
#   benchmarks: False
#
# package cardano-sl-x509
#   tests: False
#   benchmarks: False
#
# package cardano-crypto-class
#   tests: False
#   benchmarks: False
#
# package cardano-crypto-wrapper
#   tests: False
#   benchmarks: False
#
# package ouroboros-network-framework
#   tests: False
#   benchmarks: False
#
# package ouroboros-network
#   tests: False
#   benchmarks: False
#
# package byron-spec-chain
#   tests: False
#   benchmarks: False
#
# package cardano-addresses
#   tests: False
#   benchmarks: False
#
# package cardano-api
#   tests: False
#   benchmarks: False
#
# package cardano-cli
#   tests: False
#   benchmarks: False
#
# package cardano-crypto
#   tests: False
#   benchmarks: False
#
# package cardano-ledger
#   tests: False
#   benchmarks: False
#
# package cardano-node
#   tests: False
#   benchmarks: False
#
# package cardano-transactions
#   tests: False
#   benchmarks: False
#
# package lobemo-backend-monitoring
#   tests: False
#   benchmarks: False
#
# package ntp-client
#   tests: False
#   benchmarks: False
#
# package ouroboros-consensus-test-infra
#   tests: False
#   benchmarks: False
#
# package persistent
#   tests: False
#   benchmarks: False
#
# package persistent-sqlite
#   tests: False
#   benchmarks: False
#
# package persistent-template
#   tests: False
#   benchmarks: False
#
# package shelley-spec-ledger-test
#   tests: False
#   benchmarks: False
#
#+END_STACK2CABAL
