env:
  NIX_PATH: "channel:nixos-19.03"
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CACHE_DIR: "/cache/cardano-wallet"
  SCRATCH_DIR: "/scratch/cardano-wallet"

steps:
  - label: 'Restore benchmark - mainnet'
    command: "./.buildkite/bench-restore.sh"
    env:
      HOME: "/cache/cardano-wallet.home"
      NETWORK: mainnet
    timeout_in_minutes: 600
    agents:
      system: x86_64-linux

  - label: 'Restore benchmark - testnet'
    command: "./.buildkite/bench-restore.sh"
    env:
      HOME: "/cache/cardano-wallet.home"
      NETWORK: testnet
    timeout_in_minutes: 600
    agents:
      system: x86_64-linux

  - label: 'Database benchmark'
    command: "./.buildkite/bench-db.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux

  - label: 'Latency benchmark'
    command: "./.buildkite/bench-latency.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux

  - label: 'Database Migrations Test'
    commands:
      - "rm -rf state-migration-test*"
      - "nix-build nix/migration-tests.nix -o migration-tests"
      - "./migration-tests/runall.sh"
    timeout_in_minutes: 60
    agents:
      system: x86_64-linux
