######################################################################
# Adrestia/cardano-wallet configuration for go-jira.
#
# See https://github.com/go-jira/jira for documentation on how to use
# go-jira and edit these config files.
# You will need to put your login details in ~/.jira.d/config.yml.
#
######################################################################

endpoint: https://jira.iohk.io
project: ADP

custom-commands:
  - name: bugs
    help: List unresolved bug tickets
    options:
      - name: query
        short: q
    args:
      - name: terms
        required: false
    script: |-
      set -x
      {{jira}} list --template table --query "type = Bug and resolution = Unresolved and project=$JIRA_PROJECT and component = cardano-wallet{{ with args.terms }} and text ~ \"{{ args.terms }}\"{{ end }}{{ with options.query }} and {{ options.query }}{{ end }} ORDER BY priority DESC, updated DESC, rank ASC, created"

  - name: mine
    help: Display unresolved issues assigned to me
    script: |-
      {{jira}} list --template table --query "resolution = Unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"

  - name: sprint
    help: Display issues for active sprint
    script: |-
      {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = Unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"

  - name: release-notes-bugs
    help: Produce unresolved issues list for cardano-wallet release notes
    options:
      - name: minPriority
        short: p
        help: Minimum priority for query
      - name: showPriority
        type: bool
        help: Also show priority and severity in the list
        default: false
      - name: minSeverity
        help: Minimum priority for query
        default: "(1, 2)"
        hidden: true
    script: |-
      {{ if options.showPriority }}showPriority=1{{ end }} {{jira}} list --template release-notes-bugs --query "project=$JIRA_PROJECT and component = cardano-wallet and type = Bug and resolution = Unresolved{{ if options.minPriority }} and priority >= {{options.minPriority}}{{end}}{{ if options.minSeverity }} and 'Severity / Probability Score' in {{options.minSeverity}}{{end}} ORDER BY priority DESC, created" --queryfields=priority,customfield_12502

  - name: assigned
    help: What tickets we are assigned to
    script: |-
      {{jira}} list --template inprogress --query "project=$JIRA_PROJECT and statusCategory = 'In Progress' and assignee in ('rodney.lorrimar@iohk.io', 'pawel.jakubas@iohk.io', 'johannes.lund@iohk.io', 'jonathan.knowles@iohk.io', 'matthias.benkort@iohk.io', 'alex.apeldoorn@iohk.io', 'sergiy.savatyeyev@iohk.io') ORDER BY assignee ASC, updated DESC, rank ASC, created"
