name: cardano-wallet Windows Tests

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: windows-2016
    name: Download windows testing bundle
    steps:
      - name: Fetch Windows testing bundle
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-tests-win64/latest/download/1"
          $output = "cardano-wallet-tests-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - name: Save files
        uses: actions/upload-artifact@v2
        with:
          name: cardano-wallet-tests-win64
          path: "**/*"

  cardano-wallet-core-test-unit:
    name: 'cardano-wallet-core:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-core-test-unit.exe --color'

  cardano-wallet-test-unit:
    name: 'cardano-wallet:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-test-unit.exe --color'

  cardano-wallet-cli-test-unit:
    name: 'cardano-wallet-cli:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-cli-test-unit.exe --color'

  text-class-test-unit:
    name: 'test-class:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\text-class-test-unit.exe --color'

  cardano-wallet-launcher-test-unit:
    name: 'cardano-wallet-launcher:unit'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-launcher-test-unit.exe --color'
        continue-on-error: true

  cardano-wallet-test-integration:
    name: 'cardano-wallet:integration'
    needs: setup
    runs-on: windows-2016
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-test-integration.exe --color'
        timeout-minutes: 60

  finish:
    name: Finish
    runs-on: windows-2016
    needs:
      - cardano-wallet-core-test-unit
      - cardano-wallet-test-unit
      - cardano-wallet-cli-test-unit
      - text-class-test-unit
      - cardano-wallet-launcher-test-unit
      - cardano-wallet-test-integration
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Advance windows-tests-pass and all-tests-pass branches"
        shell: bash
        run: "bash .buildkite/push-branch.sh windows-tests-pass linux-tests-pass all-tests-pass"
        env:
          ACTIONS_SSH_KEY: "${{ secrets.ACTIONS_SSH_KEY }}"
