name: E2E Windows

on:
  schedule:
  - cron:  "0 23 * * *"
  workflow_dispatch:
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node db
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.NODE_DB }}
        key: ${{ runner.os }}-node-db-nightly-win-tests-${{ hashFiles('**/protocolMagicId') }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Prepare Windows
      run: |
        choco install wget
        choco install unzip
        choco install nssm

    - name: Start cardano-wallet and cardano-node
      run: |
        bundle exec rake get_latest_bins
        bundle exec rake get_latest_configs["testnet"]
        bundle exec rake start_node_and_wallet

    - name: Wait until node is synced
      run: bundle exec rake wait_until_node_synced

    - name: Run all tests
      run: bundle exec rspec .
      
    - name: 📎 Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-logs
        path: test/e2e/logs
    env:
      NODE_DB: d:/node-db-nightly-win-tests
      WALLET_DB: d:/wallet-db
      TOKEN_METADATA: http://metadata-server-mock.herokuapp.com/
