name: E2E MacOS

on:
  schedule:
  - cron:  "0 20 * * *"
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'testnet'

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Prepare MacOS
      run: brew install screen

    - name: Get Date/Time
      id: date-time
      shell: bash
      run: |
        echo "::set-output name=value::$(rake datetime)"

    - name: Cache node db
      id: cache
      uses: actions/cache@v2.1.4
      with:
        path: test/e2e/state/node_db/${{ env.NETWORK }}
        key: node-db-${{ runner.os }}-${{ env.NETWORK }}-${{ steps.date-time.outputs.value }}
        restore-keys: |
          node-db-${{ runner.os }}-${{ env.NETWORK }}-

    - name: Run all tests
      run: rake run_on[$NETWORK]

    - name: 📎 Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-logs
        path: test/e2e/state/logs

    env:
      TESTS_E2E_FIXTURES: ${{ secrets.TESTS_E2E_FIXTURES }}
      NETWORK: ${{ github.event.inputs.network || 'testnet' }}
