name: E2E MacOS

on:
  schedule:
  - cron:  "0 22 * * *"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Prepare MacOS
      run: brew install screen

    - name: Cache node db
      id: cache
      uses: actions/cache@v2
      with:
        path: test/e2e/node_db
        key: ${{ runner.os }}-node-cache

    - name: Set up cardano-wallet and cardano-node
      run: |
        bundle exec rake fixture_wallets_decode
        bundle exec rake get_latest_bins
        bundle exec rake get_latest_configs["testnet"]
        bundle exec rake start_node_and_wallet

    - name: Wait until node is synced
      run: bundle exec rake wait_until_node_synced

    - name: Run all tests
      run: bundle exec rspec .

    - name: 📎 Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-logs
        path: test/e2e/logs
