name: E2E Docker

on:
  schedule:
  - cron:  "0 23 * * *"
  workflow_dispatch:
    inputs:
      nodeTag:
        description: 'Node tag (docker)'
        required: true
        default: '1.25.1'
      walletTag:
        description: 'Wallet tag (docker)'
        required: true
        default: 'dev-master-shelley'

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Get recent configs and decode fixture_wallets.json.gpg
      run: |
        rake fixture_wallets_decode
        rake get_latest_configs["testnet"]

    - name: Cache node db
      id: cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/node-db-nightly-docker
        key: ${{ runner.os }}-node-cache

    - name: Set up cardano-wallet and cardano-node MANUAL
      if: ${{ github.event.inputs.walletTag != '' && github.event.inputs.nodeTag != ''}}
      env:
        WALLET: ${{ github.event.inputs.walletTag }}
        NODE: ${{ github.event.inputs.nodeTag }}
      run: |
        echo "Wallet: $WALLET"
        echo "Node: $NODE"
        NODE_CONFIG_PATH=`pwd`/state/configs/$NETWORK docker-compose -f docker-compose-test.yml up --detach
        ls ~/node-db-nightly-docker

    - name: Set up cardano-wallet and cardano-node NIGHTLY
      if: ${{ github.event.inputs.walletTag == '' && github.event.inputs.nodeTag == ''}}
      run: |
        echo "Wallet: $WALLET"
        echo "Node: $NODE"
        NODE_CONFIG_PATH=`pwd`/state/configs/$NETWORK docker-compose -f docker-compose-test.yml up --detach
        ls ~/node-db-nightly-docker

    - name: Display versions
      run: |
        docker run --rm inputoutput/cardano-wallet:$WALLET version
        docker run --rm inputoutput/cardano-node:$NODE version

    - name: Wait until node is synced
      run: rake wait_until_node_synced

    - name: Run all tests
      run: rake spec

    - name: Get docker logs
      if: always()
      run: rake get_docker_logs

    - name: 📎 Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-docker-logs
        path: test/e2e/state/logs

    - name: Stop docker-compose
      run: NODE_CONFIG_PATH=`pwd`/state/configs/$NETWORK docker-compose -f docker-compose-test.yml down
    env:
      TESTS_E2E_TOKEN_METADATA: https://metadata.cardano-testnet.iohkdev.io/
      TESTS_E2E_FIXTURES: ${{ secrets.TESTS_E2E_FIXTURES }}
      NETWORK: testnet
      WALLET: dev-master-shelley
      NODE: 1.25.1
