name: E2E MacOS

on:
  schedule:
  - cron:  "0 22 * * *"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Prepare MacOS
      run: brew install screen

    - name: Cache node db
      id: cache
      uses: actions/cache@v2
      with:
        path: test/e2e/state/node_db
        key: ${{ runner.os }}-node-cache

    - name: Run all tests
      run: rake run_on[testnet]

    - name: 📎 Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-logs
        path: test/e2e/state/logs

    env:
      TESTS_E2E_FIXTURES: ${{ secrets.TESTS_E2E_FIXTURES }}
